### ISSUE TITLE
Error happened today

### ISSUE THREAD

**Issue by Bussin537** [rfoel/duolingo#13]
Normally it works but when I tried it today this happened:

```
Run node index.js
undefined:1
<!doctype html>
^

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at parseJSONFromBytes (node:internal/deps/undici/undici:4[7](https://github.com/Bussin537/duolingo/actions/runs/7755659792/job/21151482138#step:4:8)47:19)
    at successSteps (node:internal/deps/undici/undici:471[8](https://github.com/Bussin537/duolingo/actions/runs/7755659792/job/21151482138#step:4:9):27)
    at fullyReadBody (node:internal/deps/undici/undici:1433:[9](https://github.com/Bussin537/duolingo/actions/runs/7755659792/job/21151482138#step:4:10))
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async specConsumeBody (node:internal/deps/undici/undici:4727:7)
    at async file:///home/runner/work/duolingo/duolingo/index.js:20:19

Node.js v[18](https://github.com/Bussin537/duolingo/actions/runs/7755659792/job/21151482138#step:4:19).[19](https://github.com/Bussin537/duolingo/actions/runs/7755659792/job/21151482138#step:4:20).0
Error: Process completed with exit code 1.
```

**Comment by Bussin537** [comment]
I created a new fork too but didn't work

**Comment by Bussin537** [comment]
The error message TypeError: Cannot read properties of undefined (reading 'find') indicates that its trying to access the property skillId of an undefined value. In JavaScript, the find() method returns the value of the first element in the array that satisfies the provided testing function. If no values satisfy the testing function, undefined is returned, and you cannot access properties of undefined.

The problematic line is:

skillId: xpGains.find(xpGain => xpGain.skillId).skillId,

**Comment by j6nca** [comment]
I was able to resolve this in my fork, you need to log in to browser with dev tools and navigate to the practice > listen practice screen. Search for the sessions requests in your network tab, it will give you a proper list of challengeTypes (not sure as to why they differ between accounts), use that list with your request in index.js and it should go through 🙂

**Comment by Aziz12341234** [comment]
This worked thank you so much

**Comment by sadeathoughts** [comment]
@j6nca I have no "listen practice" in web duolingo, could there be challengeTypes anywhere else?

**Comment by sadeathoughts** [comment]
@j6nca Hello! Unfortunately, I have no "Listen practice" in my web duolingo :(
I've found sessions request in network tab with "challengeTypes" and changed them in index.js, but that didn't help
Have you got any other ideas?

**Comment by sadeathoughts** [comment]
Hi all!
I also encountered the same problem and this is what I came to. My duolingo has two courses: English and math. Before this, the method in the instructions worked for me a couple of times (using GitHub Actions), but then it always gave me this error.
Changing challengeTypes like @j6nca did not work, and the error was actually hidden in the line “skillId: xpGains.find(xpGain => xpGain.skillId).skillId”, as @Bussin537 said.

The point is that xpGains has different skillIds for all courses that you have. And when the first course in the list was a mathematics course that had skillId: 'bt_decimals_11' - an error was thrown.

To fix this error, I added a condition and changed the line
"skillId: xpGains.find(xpGain => xpGain.skillId).skillId"
on
"xpGains.find(x => !!x.skillId && x.skillId.length > 30).skillId"
because my English courses have a skillId in the form of different letters and numbers in the amount of 32 pieces.

Tag me if my solution doesn't work for you, I'll try to help

**Comment by Javi17mod** [comment]
@sadeathoughts , the code doesnt work, it show me this error: 
file:///home/runner/work/duolingo/duolingo/index.js:68
skillId: xpGains.find(xpGain => xpGain.skillId).skillId,
                                               ^

TypeError: Cannot read properties of undefined (reading 'skillId')
    at file:///home/runner/work/duolingo/duolingo/index.js:6[8](https://github.com/Javi17mod/duolingo/actions/runs/7927039862/job/21642755912#step:4:9):48
    at process.processTicksAndRejections (node:internal/process/task_queues:[9](https://github.com/Javi17mod/duolingo/actions/runs/7927039862/job/21642755912#step:4:10)5:5)

Node.js v18.19.0
Error: Process completed with exit code 1.

**Comment by sadeathoughts** [comment]
@Javi17mod that means the xpGains has not any objects with defined skillid (or just empty array)
try to find out what is in your xpGains
can I dm u somewhere?

**Comment by rfoel** [comment]
Hey everyone, I've updated the script and simplified it a bit, removing the need for `xpGains` completely. Update your forks and see if that works.

**Comment by Javi17mod** [comment]
Hey @rfoel , if you enter my fork, I have a small code, that shows like 1000/0 0% off the exp earned, if you want, you can see it and use it, now it works

**Comment by rfoel** [comment]
@Javi17mod what did you modify exactly? Is something still broken?

**Comment by Javi17mod** [comment]
No, just a simple console log system, and you put the console log in the incorrect place, put it in the
`).then((response) => response.json());

		xp += response.xpGain; `
Part, and help me because I win less and slower xp @rfoel

**Comment by rfoel** [comment]
Oh I see.The way I implemented it will only work if the code does not break. I have seen people trying to do 100 lessons in one go and this will certainly break at some point, so they would never see the end gains. Yours implementation makes sense, but I don't see a reason to change the code now.
About the less and slower XP, this happens because the lesson type, which will not depend on the "skillId", gives 10 XP per lesson instead of the usual 20 for speaking or listening lessons. I think that's fine because the main intent of this repo is to keep the streak, not really farm XP. Farming XP is a possibility but not the main goal.

**Comment by Javi17mod** [comment]
Ok, but the code, when you are seeing the console, it doesn’t log anithyng, but if it fails, it will show the error

**Comment by GhostLemonPie** [comment]
I got the same error when trying to run 'Do a Duolingo lesson' 

In my case, I have tested with 2 new account and worked
So I discovered that the problem happened only with old account with old courses maybe, somehow returned something unexpected maybe. I don't understand much about code yet.

After discovery this I erased all old courses and started a new one, and now the script is working for this account

**Comment by Javi17mod** [comment]
@GhostLemonPie , delete my fork, or consequences will happend, but I can help if you give me access
